server:
  port: 8080

spring:
  messages:
    basename: i18n/messages
  datasource:
    url: jdbc:postgresql://8.210.211.217:5432/lock_market
    username: g38
    password: YkwrJ5D2X
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: 'turayevhasan2003@gmail.com'
    password: 'tiii chrr wrtz tnak'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true